services:
  - type: web
    name: finddoctor-backend
    env: java
    plan: free
    repo: https://github.com/nitahun/find-doctor-webapp
    branch: main
    rootDir: backend
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/finddoctor-0.0.1-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://your-db-host:3306/your-db-name
      - key: SPRING_DATASOURCE_USERNAME
        value: your-db-user
      - key: SPRING_DATASOURCE_PASSWORD
        value: your-db-password
